[package]
name = "jedinft"
version = "1.0.0"
description = "NFT Contract For LP Contest"
# homepage = "https://github.com/auditless/cairo-template"


[dependencies]
starknet = ">=2.2.0"
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs-list.name = "experimental"